# 🔒 BMAD MCP ENTERPRISE SECURITY CONFIGURATION
# Agent: contains-test-analyzer + bmad-qa
# Version: 1.0.0
# Classification: ENTERPRISE CONFIDENTIAL

enterprise_security:
  version: "1.0.0"
  deployment_mode: "production"
  compliance_level: "enterprise"
  security_posture: "zero_trust"
  
  # Configuration globale sécurité
  global_settings:
    enabled: true
    strict_mode: true
    fail_safe: true
    audit_everything: true
    immutable_logs: true
    
  # Authentification & Autorisation
  authentication:
    method: "mutual_tls"
    certificate_authority: "/security/certs/bmad-ca.pem"
    certificate_rotation_days: 30
    key_length: 4096
    algorithms_allowed: ["RSA-4096", "ECDSA-P384"]
    algorithms_forbidden: ["RSA-1024", "RSA-2048", "MD5", "SHA1"]
    
    session_management:
      timeout_minutes: 60
      max_concurrent_sessions: 5
      session_binding: "certificate_fingerprint"
      
  authorization:
    model: "zero_trust_rbac"
    default_policy: "DENY"
    permissions_matrix: "/security/mcp-permissions-matrix-detailed.json"
    dynamic_permissions: true
    approval_workflows:
      - risk_level: "CRITICAL"
        approvers: ["security_manager", "ciso"]
        timeout_hours: 2
      - risk_level: "HIGH" 
        approvers: ["security_team_lead"]
        timeout_hours: 8
        
  # Chiffrement
  encryption:
    in_transit:
      protocol: "TLS_1_3"
      cipher_suites:
        - "TLS_AES_256_GCM_SHA384"
        - "TLS_CHACHA20_POLY1305_SHA256"
        - "TLS_AES_128_GCM_SHA256"
      certificate_validation: "strict"
      
    at_rest:
      algorithm: "AES_256_GCM"
      key_management: "enterprise_vault"
      key_rotation_days: 90
      
  # Audit & Logging
  audit_logging:
    config_file: "/security/audit-logging-config.yaml"
    immutable_storage: true
    real_time_processing: true
    retention_years: 7
    compliance_tags: ["SOC2", "ISO27001", "GDPR"]
    
  # Monitoring sécurité temps réel
  security_monitoring:
    enabled: true
    monitoring_script: "/security/realtime-security-monitoring.py"
    detection_threshold: "3_sigma"
    response_time_seconds: 300
    
    alerting:
      channels: ["email", "slack", "pagerduty"]
      severity_mapping:
        CRITICAL: ["email", "slack", "pagerduty", "sms"]
        HIGH: ["email", "slack", "pagerduty"] 
        MEDIUM: ["email", "slack"]
        LOW: ["email"]
        
  # Tests sécurité
  security_testing:
    test_suite: "/security/security-tests-suite.py"
    schedule: "daily"
    automated_remediation: true
    compliance_validation: true
    
  # Incident Response
  incident_response:
    playbooks_directory: "/security/playbooks/"
    response_team: "security@company.com"
    escalation_matrix: "/security/audit-trails-incident-response.md#escalation-matrix"
    forensic_retention_years: 10
    
  # Intégration MCP Servers
  mcp_server_security:
    github:
      permissions: ["read", "write", "admin"]
      risk_level: "HIGH"
      monitoring: "enhanced"
      audit_level: "L1"
      
    postgres:
      permissions: ["read", "write", "schema_modify"] 
      risk_level: "HIGH"
      monitoring: "enhanced"
      audit_level: "L1"
      encryption_required: true
      
    redis:
      permissions: ["read", "write", "flush", "config"]
      risk_level: "MEDIUM"
      monitoring: "standard"
      audit_level: "L2"
      namespace_isolation: true
      
    firecrawl:
      permissions: ["read", "scrape"]
      risk_level: "MEDIUM"
      monitoring: "standard"
      audit_level: "L2"
      rate_limiting: true
      
    notion:
      permissions: ["read", "write"]
      risk_level: "LOW"
      monitoring: "standard"
      audit_level: "L3"
      
    shadcn:
      permissions: ["read", "install"]
      risk_level: "LOW"
      monitoring: "standard"
      audit_level: "L3"
      
    filesystem:
      permissions: ["read", "write", "execute"]
      risk_level: "CRITICAL"
      monitoring: "enhanced"
      audit_level: "L1"
      path_isolation: true
      
    memory:
      permissions: ["read", "write"]
      risk_level: "MEDIUM"
      monitoring: "standard"
      audit_level: "L2"
      encryption_required: true

  # Configuration agents BMAD
  bmad_agents_security:
    bmad-orchestrator:
      security_clearance: "L1_CRITICAL"
      audit_level: "maximum"
      isolation_level: "high"
      resource_limits:
        cpu_percent: 50
        memory_mb: 2048
        disk_mb: 5120
        
    bmad-parallel-orchestrator:
      security_clearance: "L1_CRITICAL"
      audit_level: "maximum" 
      isolation_level: "high"
      hook_execution_sandbox: true
      
    contains-test-analyzer:
      security_clearance: "L2_HIGH"
      audit_level: "enhanced"
      isolation_level: "medium"
      read_only_access: true
      
    contains-eng-devops:
      security_clearance: "L1_CRITICAL"
      audit_level: "maximum"
      isolation_level: "high"
      deployment_approval_required: true
      
  # Conformité réglementaire
  compliance:
    soc2:
      enabled: true
      controls: ["CC6.1", "CC6.2", "CC6.3", "CC7.1", "CC7.2"]
      reporting_frequency: "monthly"
      
    iso27001:
      enabled: true
      controls: ["A.9.4.2", "A.12.6.1", "A.16.1.1"]
      certification_body: "external_auditor"
      
    gdpr:
      enabled: true
      data_protection_officer: "dpo@company.com"
      breach_notification_hours: 72
      
    nist_csf:
      enabled: true
      framework_version: "2.0"
      maturity_target: "optimized"
      
  # Métriques & KPI
  security_metrics:
    collection_frequency: "real_time"
    dashboard_url: "https://security-dashboard.company.com"
    
    targets:
      mttd_minutes: 5      # Mean Time To Detect
      mttr_minutes: 15     # Mean Time To Respond  
      mttc_minutes: 60     # Mean Time To Contain
      false_positive_rate: 0.03  # < 3%
      availability_percent: 99.9
      
  # Sauvegarde & Recovery
  backup_recovery:
    security_configs:
      frequency: "daily"
      retention_days: 365
      encryption: "AES_256"
      
    audit_logs:
      frequency: "hourly"
      retention_years: 7
      immutable_storage: true
      
    forensic_evidence:
      retention_years: 10
      chain_of_custody: true
      legal_hold_capable: true
      
  # Formation & Sensibilisation
  security_training:
    mandatory_training: "annual"
    incident_response_drills: "quarterly"
    phishing_simulations: "monthly"
    compliance_updates: "as_needed"
    
  # Contacts d'urgence
  emergency_contacts:
    primary: "security@company.com"
    escalation_l1: "security-manager@company.com"
    escalation_l2: "ciso@company.com"
    escalation_l3: "ceo@company.com"
    
    external:
      cyber_insurance: "claims@cyberinsurance.com"
      legal_counsel: "legal@law-firm.com"
      law_enforcement: "cybercrime@fbi.gov"

# Configuration environnements
environments:
  production:
    security_level: "maximum"
    monitoring_level: "enhanced"
    alerting_level: "all"
    
  staging:
    security_level: "high"
    monitoring_level: "standard"
    alerting_level: "critical_high"
    
  development:
    security_level: "medium"
    monitoring_level: "basic"
    alerting_level: "critical_only"

# Automatisation sécurité
automation:
  enabled: true
  
  auto_responses:
    brute_force_attempt:
      action: "temporary_lockout"
      duration_minutes: 30
      
    privilege_escalation:
      action: "immediate_lockout"
      notification: "immediate"
      
    data_exfiltration_indicators:
      action: "emergency_response"
      isolation: "complete"
      
    compliance_violation:
      action: "enhanced_monitoring"
      reporting: "immediate"
      
  remediation_scripts:
    certificate_rotation: "/security/scripts/rotate-certificates.sh"
    user_lockout: "/security/scripts/lockout-user.sh"  
    system_isolation: "/security/scripts/isolate-system.sh"
    evidence_collection: "/security/scripts/collect-evidence.sh"